// Generate mock units for demo
function generateMockUnits() {
  const mockUnits = [
    {
      _id: "1",
      unit_number: "A-101",
      property: { _id: "1", name: "Sunrise Apartments" },
      type: "2BHK",
      area: 1200,
      area_unit: "sqft",
      floor: 1,
      rent: 25000,
      security_deposit: 50000,
      status: "available",
      amenities: ["AC", "Parking", "Elevator"],
      description: "Spacious 2BHK apartment with modern amenities",
      maintenance_fee: 2000,
    },
    {
      _id: "2",
      unit_number: "B-205",
      property: { _id: "2", name: "Downtown Plaza" },
      type: "3BHK",
      area: 1500,
      area_unit: "sqft",
      floor: 2,
      rent: 35000,
      security_deposit: 70000,
      status: "occupied",
      amenities: ["AC", "Parking", "Gym", "Pool"],
      description: "Luxury 3BHK with premium amenities",
      maintenance_fee: 3000,
      current_tenant: { name: "John Doe", phone: "+91 9876543210" },
    },
    {
      _id: "3",
      unit_number: "C-302",
      property: { _id: "3", name: "Garden View Complex" },
      type: "1BHK",
      area: 800,
      area_unit: "sqft",
      floor: 3,
      rent: 18000,
      security_deposit: 36000,
      status: "maintenance",
      amenities: ["Balcony", "Elevator", "Security"],
      description: "Cozy 1BHK with garden view",
      maintenance_fee: 1500,
    },
    {
      _id: "4",
      unit_number: "D-401",
      property: { _id: "1", name: "Sunrise Apartments" },
      type: "Studio",
      area: 600,
      area_unit: "sqft",
      floor: 4,
      rent: 15000,
      security_deposit: 30000,
      status: "reserved",
      amenities: ["AC", "Furnished", "Wifi"],
      description: "Modern studio apartment",
      maintenance_fee: 1000,
    },
    {
      _id: "5",
      unit_number: "E-501",
      property: { _id: "2", name: "Downtown Plaza" },
      type: "4BHK",
      area: 2000,
      area_unit: "sqft",
      floor: 5,
      rent: 50000,
      security_deposit: 100000,
      status: "available",
      amenities: ["AC", "Parking", "Gym", "Pool", "Balcony"],
      description: "Spacious 4BHK penthouse style",
      maintenance_fee: 4000,
    },
  ];
  units = mockUnits;
}
